// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlyWear.Api.Data;

#nullable disable

namespace OnlyWear.Api.Migrations
{
    [DbContext(typeof(OnlyWearDbContext))]
    [Migration("20260913100144_InicialOnlyWear")]
    partial class InicialOnlyWear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlyWear.Api.Entities.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("DisenoPersonalizadoId")
                        .HasColumnType("integer");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisenoPersonalizadoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido", t =>
                        {
                            t.HasCheckConstraint("CK_DetallePedido_ProductoODiseno", "(\"ProductoId\" IS NOT NULL AND \"DisenoPersonalizadoId\" IS NULL) OR (\"ProductoId\" IS NULL AND \"DisenoPersonalizadoId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.DisenoPersonalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Escala")
                        .HasColumnType("real");

                    b.Property<string>("ImagenClienteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PosicionX")
                        .HasColumnType("real");

                    b.Property<float>("PosicionY")
                        .HasColumnType("real");

                    b.Property<string>("TalleElegido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DisenosPersonalizados");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.PrecioPorTalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Talle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("PreciosPorTalle");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.DetallePedido", b =>
                {
                    b.HasOne("OnlyWear.Api.Entities.DisenoPersonalizado", "DisenoPersonalizado")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("DisenoPersonalizadoId");

                    b.HasOne("OnlyWear.Api.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlyWear.Api.Entities.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("ProductoId");

                    b.Navigation("DisenoPersonalizado");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.DisenoPersonalizado", b =>
                {
                    b.HasOne("OnlyWear.Api.Entities.Usuario", "Usuario")
                        .WithMany("Disenos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Pedido", b =>
                {
                    b.HasOne("OnlyWear.Api.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.PrecioPorTalle", b =>
                {
                    b.HasOne("OnlyWear.Api.Entities.Producto", "Producto")
                        .WithMany("Precios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.DisenoPersonalizado", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Producto", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Precios");
                });

            modelBuilder.Entity("OnlyWear.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Disenos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
